
[hashids]
  length = 12
  secret = "6ab6122836cfef95f8db"

[jwt]
  expireduration = 24
  secret = "i1ydX9RtHyuJTrw7frcu"

[language]
  local = "zh-cn"

[mail]
  host = "smtp.163.com"
  pass = ""
  port = 465
  to = ""
  user = ""

[mysql]

  [mysql.base]
    connmaxlifetime = 60
    maxidleconn = 60
    maxopenconn = 10

  [mysql.read]
    addr = "xh.skyzhou.cn:3306"
    name = "gga"
    pass = "Xhsoftware123"
    user = "root"

  [mysql.write]
    addr = "xh.skyzhou.cn:3306"
    name = "gga"
    pass = "Xhsoftware123"
    user = "root"

[redis]
  addr = "xh.skyzhou.cn:6379"
  db = "1"
  maxretries = 3
  minidleconns = 5
  pass = "Xhsoftware123"
  poolsize = 10

[urltoken]
  expireduration = 10
  secret = "i1ydX9RtHyuJTrw7frcu"
